- name: installong catalogue service
  hosts: all
  become: true
  tasks:
    - name: Install the latest version of Apache
      ansible.builtin.yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: installed
        disable_gpg_check: true

    - name: downloading nodejs repo
      ansible.builtin.shell: yum module enable redis:remi-6.2 -y

    - name: installing redis
      ansible.builtin.yum:
        name: redis
        state: latest

    - name: Replace old hostname with new hostname
      ansible.builtin.replace:
        path: /etc/redis.conf
        regexp: 127.0.0.1
        replace: 0.0.0.0

    - name: Replace old hostname with new hostname
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: 127.0.0.1
        replace: 0.0.0.0

    - name: Restart service catalogue,
      ansible.builtin.service:
        name: redis
        state: restarted
        enabled: yes
        daemon_reload: true

