- name: installing nginx
  hosts: all
  become: true
  tasks:
   - name: install nginixx
     ansible.builtin.yum:
        name: nginx
        state: latest

- name: Start nginx
  ansible.builtin.systemd:
     name: nginx
     state: started
     enabled: yes