- name: installing nginx
  hosts: all
  become: true
  tasks:
   - name: install nginixx
     ansible.builtin.yum:
        name: nginx
        state: latest

- name: Start service nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes