- name: installing user service
  hosts: all
  become: true
  tasks:
    - name: downloading nodejs repo
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

    - name: installing nodejs
      ansible.builtin.yum:
        name: nodejs
        state: latest

    - name: Add app user
      ansible.builtin.user:
        name: roboshop

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Unzip and download
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/user.zip
        dest: /app
        remote_src: yes

    - name: dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app

    - name: Copying service file
      ansible.builtin.copy:
        src: user.service
        dest: /etc/systemd/system/user.service

    - name: Restart service user,
      ansible.builtin.service:
        name: user
        state: restarted
        enabled: yes
        daemon_reload: true

    - name: Copying service file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: installing mongod
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: latest

    - name: schema loading
      ansible.builtin.shell: mongo --host mongodb-dev.cloudev7.online </app/schema/user.js