- name: downloading nodejs repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: installing nodejs
  ansible.builtin.yum:
    name: nodejs
    state: latest

- name: importing tasks
  ansible.builtin.import_tasks:
      file: req.yml

- name: dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Copying service file
  ansible.builtin.copy:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: Restart service {{component}},
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted
    enabled: yes
    daemon_reload: true

- name: Copying service file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
  when: schema is defined

- name: installing mongod
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: latest
  when: schema is defined

- name: schema loading
  ansible.builtin.shell: mongo --host mongodb-dev.cloudev7.online </app/schema/{{component}}.js
  when: schema is defined